spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apelearn?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      use-global-data-source-stat: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      remove-abandoned-timeout: 1800
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
        allow: 127.0.0.1
        deny: 10.251.0.78
        reset-enable: false
        #http://127.0.0.1:8080/druid/index.htm

logging:
  level:
    com.greatld.creditmetrics.mapper: debug