server:
  port: 8089

spring:
  profiles:
    active: prod #默认为开发环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.apelearn.crypto.domain
  configuration:
    #不打印查询结果
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    #打印sql、参数、查询结果
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






